// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'movie.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Autogenerated _$AutogeneratedFromJson(Map<String, dynamic> json) {
  return Autogenerated()
    ..rating = json['rating'] == null
        ? null
        : Rating.fromJson(json['rating'] as Map<String, dynamic>)
    ..reviewsCount = json['reviewsCount'] as int
    ..wishCount = json['wishCount'] as int
    ..doubanSite = json['doubanSite'] as String
    ..year = json['year'] as String
    ..images = json['images'] == null
        ? null
        : Images.fromJson(json['images'] as Map<String, dynamic>)
    ..alt = json['alt'] as String
    ..id = json['id'] as String
    ..mobileUrl = json['mobileUrl'] as String
    ..title = json['title'] as String
    ..doCount = json['doCount']
    ..shareUrl = json['shareUrl'] as String
    ..seasonsCount = json['seasonsCount']
    ..scheduleUrl = json['scheduleUrl'] as String
    ..episodesCount = json['episodesCount']
    ..countries = (json['countries'] as List)?.map((e) => e as String)?.toList()
    ..genres = (json['genres'] as List)?.map((e) => e as String)?.toList()
    ..collectCount = json['collectCount'] as int
    ..casts = (json['casts'] as List)
        ?.map(
            (e) => e == null ? null : Casts.fromJson(e as Map<String, dynamic>))
        ?.toList()
    ..currentSeason = json['currentSeason']
    ..originalTitle = json['originalTitle'] as String
    ..summary = json['summary'] as String
    ..subtype = json['subtype'] as String
    ..directors = (json['directors'] as List)
        ?.map((e) =>
            e == null ? null : Directors.fromJson(e as Map<String, dynamic>))
        ?.toList()
    ..commentsCount = json['commentsCount'] as int
    ..ratings_count = json['ratings_count'] as int
    ..aka = (json['aka'] as List)?.map((e) => e as String)?.toList();
}

Map<String, dynamic> _$AutogeneratedToJson(Autogenerated instance) =>
    <String, dynamic>{
      'rating': instance.rating,
      'reviewsCount': instance.reviewsCount,
      'wishCount': instance.wishCount,
      'doubanSite': instance.doubanSite,
      'year': instance.year,
      'images': instance.images,
      'alt': instance.alt,
      'id': instance.id,
      'mobileUrl': instance.mobileUrl,
      'title': instance.title,
      'doCount': instance.doCount,
      'shareUrl': instance.shareUrl,
      'seasonsCount': instance.seasonsCount,
      'scheduleUrl': instance.scheduleUrl,
      'episodesCount': instance.episodesCount,
      'countries': instance.countries,
      'genres': instance.genres,
      'collectCount': instance.collectCount,
      'casts': instance.casts,
      'currentSeason': instance.currentSeason,
      'originalTitle': instance.originalTitle,
      'summary': instance.summary,
      'subtype': instance.subtype,
      'directors': instance.directors,
      'commentsCount': instance.commentsCount,
      'ratings_count': instance.ratings_count,
      'aka': instance.aka
    };

Rating _$RatingFromJson(Map<String, dynamic> json) {
  return Rating()
    ..max = json['max'] as int
    ..average = (json['average'] as num)?.toDouble()
    ..stars = json['stars'] as String
    ..min = json['min'] as int;
}

Map<String, dynamic> _$RatingToJson(Rating instance) => <String, dynamic>{
      'max': instance.max,
      'average': instance.average,
      'stars': instance.stars,
      'min': instance.min
    };

Images _$ImagesFromJson(Map<String, dynamic> json) {
  return Images()
    ..small = json['small'] as String
    ..large = json['large'] as String
    ..medium = json['medium'] as String;
}

Map<String, dynamic> _$ImagesToJson(Images instance) => <String, dynamic>{
      'small': instance.small,
      'large': instance.large,
      'medium': instance.medium
    };

Casts _$CastsFromJson(Map<String, dynamic> json) {
  return Casts()
    ..alt = json['alt'] as String
    ..avatars = json['avatars'] == null
        ? null
        : Avatars.fromJson(json['avatars'] as Map<String, dynamic>)
    ..name = json['name'] as String
    ..id = json['id'] as String;
}

Map<String, dynamic> _$CastsToJson(Casts instance) => <String, dynamic>{
      'alt': instance.alt,
      'avatars': instance.avatars,
      'name': instance.name,
      'id': instance.id
    };

Avatars _$AvatarsFromJson(Map<String, dynamic> json) {
  return Avatars()
    ..small = json['small'] as String
    ..large = json['large'] as String
    ..medium = json['medium'] as String;
}

Map<String, dynamic> _$AvatarsToJson(Avatars instance) => <String, dynamic>{
      'small': instance.small,
      'large': instance.large,
      'medium': instance.medium
    };

Directors _$DirectorsFromJson(Map<String, dynamic> json) {
  return Directors()
    ..alt = json['alt'] as String
    ..avatars = json['avatars'] == null
        ? null
        : Avatars.fromJson(json['avatars'] as Map<String, dynamic>)
    ..name = json['name'] as String
    ..id = json['id'] as String;
}

Map<String, dynamic> _$DirectorsToJson(Directors instance) => <String, dynamic>{
      'alt': instance.alt,
      'avatars': instance.avatars,
      'name': instance.name,
      'id': instance.id
    };
